### PR TITLE
bump minimum supported GPDB versions

### PR DESCRIPTION
**Pull request by kalensk**
Pipeline: https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/gpupgrade:bumpMinVersions

### CODE REVIEW

**Review by jimmyyih — APPROVED** [review]

**Review by kyeap-vmware — APPROVED** [review]

**Comment by li-bupt** [comment]
Hi, I would like to know why the minimum version was updated to 6.24? Are there any issues with using gpupgrade in previous versions？(⊙o⊙)

**Comment by kalensk** [comment]
> Does this mean that I can port the latest pg_upgrade to an older version of gp and upgrade without version checking?

I don't think I understand your question. Can you be more specific in what you are asking and trying to do? 

With this update gpupgrade requires GPDB server 5.29.10 and 6.24.0. This is there for the safety and benefit of the user as explained above since there are pg_upgrade fixes and features some of which are required.

**Comment by li-bupt** [comment]
I found that gp6 to gp7 upgrade is supported in the code, so I want to try to upgrade 6.21.1 gp version to 7.0. Can I port 6.24 pg_upgrade to 6.21.1 gp and then use gpupgrade? :-)

**Comment by li-bupt** [comment]
Thank you for such a detailed reply!

**Pull request merged**
