### PR TITLE
substep: add ConditionallyRun

### PR DESCRIPTION
**Pull request by kalensk**
(Refer to the last commit as this PR is currently based on https://github.com/greenplum-db/gpupgrade/pull/557, but does not matter. Which ever one goes in first is fine as long as they are updated accordingly.)

Skip steps and print a log message based on the shouldRun parameter.

Pipeline: https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/gpupgrade:maybeRun

### CODE REVIEW

**Comment by dkrieger-pvtl** [comment]
`MaybeRun` perhaps can be renamed to some synonym of `Maybe`...I am left wondering what `Maybe` refers to, and that word seems to not be used much in software engineering literature.    Maybe(!) `ConditionallyRun` or `RunConditionally` as `condition` is a well established software language word(as in the `condition` of an if clause).

**Comment by kalensk** [comment]
> MaybeRun perhaps can be renamed to some synonym of Maybe...I am left wondering what Maybe refers to, and that word seems to not be used much in software engineering literature. Maybe(!) ConditionallyRun or RunConditionally as condition is a well established software language word(as in the condition of an if clause)

Updated to `ConditionallyRun`.

**Comment by dkrieger-pvtl** [comment]
I like the idea of the new code but think it is more readable with the condition first.  For example, instead of:

`st.RunConditionally(idl.Substep_UPGRADE_STANDBY, s.Source.HasStandby(), func(streams step.OutStreams) error`

do this:

`st.RunConditionally(s.Source.HasStandby(), idl.Substep_UPGRADE_STANDBY, func(streams step.OutStreams) error`

**Review by soumyadeep2007 — APPROVED** [review]
LGTM

**Pull request merged**
