### PR TITLE
Move general interface for Outstreams to utils package.

### PR DESCRIPTION
**Pull request by berlin-ab**
I realized while working on another PR that the utils package depended on
the step package for OutStreams, which seems like a strange dependency.

### CODE REVIEW

**Comment by jchampio** [comment]
I've been trying to move us away from the `utils` megadependency; I think this pushes things in the wrong direction.

**Comment by berlin-ab** [comment]
> I've been trying to move us away from the `utils` megadependency; I think this pushes things in the wrong direction.

I understand and agree with you, but `utils` is a better spot than `step`.

**Comment by jchampio** [comment]
> utils is a better spot than step

Why?

**Comment by berlin-ab** [comment]
Currently:

hub depends on step (specfic to specific)
utils depends on step (general to specific)

We want to depend in from specific to general.

New:

hub -> utils
step -> utils

**Comment by berlin-ab** [comment]
Can you think of a better spot to put it?

**Comment by berlin-ab** [comment]
Also, currently the Cluster knows about `step` for start/stop, which doesn't seem like something it should know about.

**Comment by berlin-ab** [comment]
Alternatively, we could duplicate the Outstreams into the `greenplum` package so there's not a dependency structure like this:

```
greenplum -> step
hub -> step
```

it would be more like:

```
hub -> greenplum (OutStreams)
hub -> step (OutStreams)
```

They can evolve independently, as long as hub ensures that it passes the necessary stream type to the `greenplumRunner`.

**Comment by jchampio** [comment]
> Currently:
> 
> hub depends on step (specfic to specific)
> utils depends on step (general to specific)

`utils.Cluster` depends on `step`, but we already know `Cluster` doesn't belong in `utils` anyway. Having a `greenplum` -> `step` dependency is less problematic to me. Not clean, but not incredibly dirty as long as the dependency doesn't grow.

> Alternatively, we could duplicate the Outstreams into the greenplum package so there's not a dependency structure like this:

I don't think the `step` dependency is a problem in practice, but it's definitely a smell. If we want to remove the `greenplum` -> `step` dependency, this move gets my vote for now.

**Comment by jchampio** [comment]
(Long-term -- and I do mean long-term; I wouldn't want to do it now -- it seems like `OutStreams` is an `io` concept. Do we have other such input/output concerns in other places?)

**Comment by berlin-ab** [comment]
@jchampio https://github.com/greenplum-db/gpupgrade/pull/272

**Comment by berlin-ab** [comment]
Closing in favor of alternate design.

**Pull request closed without merging**
