### PR TITLE
Generate bash completion

### PR DESCRIPTION
**Pull request by jchampio**
It's easy! To get the goodies,

    source ./cli/bash/bash-completion.sh

Since the root `cobra.Command` is now needed from two executables, we've moved it into the `cli/commands` package.

### CODE REVIEW

**Comment by chrishajas** [comment]
Does this also autocomplete flags?

**Comment by jchampio** [comment]
@chrishajas Yep!

```sh
$ gpupgrade prepare init <tab><tab><tab>
--new-bindir=  --old-bindir=

**Comment by nadeemg** [comment]
Can we add a line to the README also?

**Comment by jchampio** [comment]
@nadeemg Done.

**Pull request merged**
