### PR TITLE
Give the cluster the responsibility of creating the GreenplumRunner

### PR DESCRIPTION
**Pull request by berlin-ab**
Renames GreenplumRunner to `greenplum.Runner` and move it into this package along with Cluster and SegConfig.

### CODE REVIEW

**Comment by berlin-ab** [comment]
Along with my other PR for creating a greenplum package, this PR makes more sense.

**Comment by jchampio** [comment]
pure bikeshed: `c.Source.MakeRunner(streams)` or `greenplum.NewRunner(c.Source, streams)`? I like this move either way.

**Comment by berlin-ab** [comment]
> pure bikeshed: `c.Source.MakeRunner(streams)` or `greenplum.NewRunner(c.Source, streams)`? I like this move either way.

I considered this, but was waiting for a second opinion to tip me over. Thanks. I'd rather the Runner be coupled to the Cluster than the Cluster be coupled to the Runner.

**Comment by jchampio** [comment]
> I'd rather the Runner be coupled to the Cluster than the Cluster be coupled to the Runner.

Agreed!

**Pull request merged**
